# Generated by Django 6.0.4 on 2026-05-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_is_settled_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=32, unique=True, verbose_name='ID заказа'),
        ),
    ]
